### ISSUE TITLE
'serializingData()' is only available in macOS 10.15 or newer

### ISSUE THREAD

**Issue by mathisHeidrich** [alexiscn/SubsonicKit#1]
I added the package to my project and added the code you provided. When I try to build my app I get the following error: `SubsonicKit/SubsonicClient.swift:908:98 'serializingData(automaticallyCancelling:dataPreprocessor:emptyResponseCodes:emptyRequestMethods:)' is only available in macOS 10.15 or newer`
I made sure that the deployment target is 12.4 but I still get the same error.
Do you need additional information?
Thanks in advance!

**Comment by alexiscn** [comment]
fix in commit [27657f5](https://github.com/alexiscn/SubsonicKit/commit/27657f5ddaae9fdad6158c6ad7bb25b9ea47062e)

**Comment by mathisHeidrich** [comment]
Thank you for your fast fix!
